language: c++

compiler:
    - g++

notifications:
    email:
        recipients:
            - jnunezra@onera.com

before_install:
    - git clone https://github.com/spack/spack.git
    - cd spack/bin
    - ./spack install zlib
    - cd -
    #- pip install --user cpp-coveralls

env:
    matrix:
       # Serial build and test
       - CONFIGURE_COMMAND="g++ test.cpp -o test"
         TEST_SCRIPT=./test

install:
    # Compile the test code
    - echo $CONFIGURE_COMMAND
    - $CONFIGURE_COMMAND

script:
    # Run the test
    - $TEST_SCRIPT

#after_success:
#  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
