language: c++

compiler:
    - g++

notifications:
    email:
        recipients:
            - test@test.com

env:
    matrix:
       # Serial build and test
       - CONFIGURE_COMMAND="g++ --enable-gcov test.cpp -o test"
         TEST_SCRIPT=./test

install:
    # Compile the test code
    - echo $CONFIGURE_COMMAND
    - $CONFIGURE_COMMAND

script:
    # Run the test
    - $TEST_SCRIPT

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
